name: Java CI Test

on:
  pull_request:
    branches:
      #- cyclop-master-stream7
      - feature/pipline-BC-BJS2-40721
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x test